export const ROUTES = {
  index: '/',
  login: '/login',
  recuperarSenha: '/recuperar-senha',
  redefinirSenha: '/redefinir-senha',
  hub: '/hub',
  connect: {
    root: '/connect',
    index: '/connect',
    alunos: '/connect/alunos',
    professores: '/connect/professores',
    usuarios: '/connect/usuarios',
    turmas: '/connect/turmas',
    cursos: '/connect/cursos',
    empresas: '/connect/empresas',
    frequencia: '/connect/frequencia',
    gerenciarFrequencia: '/connect/gerenciar-frequencia',
    relatorios: '/connect/relatorios',
    localizacao: '/connect/localizacao',
    contratos: '/connect/contratos',
    contratoAlunos: '/connect/contrato-alunos',
    salario: '/connect/salario',
  },
  grid: {
    root: '/grid',
    index: '/grid',
    chamados: '/grid/chamados',
    tarefas: '/grid/tarefas',
    relatorios: '/grid/relatorios',
    estoque: '/grid/estoque',
    mapaTarefas: '/grid/mapa-tarefas',
    usuarios: '/grid/usuarios',
  },
  safe: {
    root: '/safe',
    index: '/safe',
    autorizacoes: '/safe/autorizacoes',
    aprovacoes: '/safe/aprovacoes',
    portaria: '/safe/portaria',
  },
  aluno: {
    dashboard: '/aluno/dashboard',
    frequencia: '/aluno/frequencia',
    grade: '/aluno/grade',
    perfil: '/aluno/perfil',
  },
} as const;
